version: '3'
services:
  banda_openmrs_service_master:
    container_name: banda_openmrs_master
    image: openhmis/openmrs-docker:latest
    #uncomment below to build image and comment out the above image line
    #build:
    #  context: .
    restart: unless-stopped
    environment:
      - DB_NAME=openmrs
      - OPENMRS_MYSQL_HOST=banda_mysql_service_master
      - OPENMRS_MYSQL_PORT=3306
      # Uncomment to load demo data
      - DEMO_DATA=1
      - DB_USER=root
      - DB_PASS=9xBgBLCdGsENs9yJLzq5bB48dp0D5kv65
      #- EXCLUDE_OPENHMIS=1
    depends_on:
      - banda_mysql_service_master
    links:
      - banda_mysql_service_master:mysql
    ports:
      - 9901:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - banda_openmrs_volume_master:/root/.OpenMRS
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  banda_mysql_service_master:
    container_name: banda_mysql_master
    image: mysql/mysql-server:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=9xBgBLCdGsENs9yJLzq5bB48dp0D5kv65
      - MYSQL_ROOT_HOST=172.%    # Allow docker contatiners to connect to mysql
    ports:
      - 3309:3306
    healthcheck:
      test: "exit 0"
    volumes:
      - banda_mysql_volume_master:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  banda_mysql_volume_master:
  banda_openmrs_volume_master:
