version: '3'
services:
  bandahealth_bk_service:
    container_name: bandahealth_bk
    image: openhmis/openmrs-docker:bk
    #uncomment below to build image and comment out the above image line
    #build:
    #  context: .
    restart: unless-stopped
    environment:
      - DB_NAME=openmrs
      - OPENMRS_MYSQL_HOST=bandahealth_bk_mysql
      - OPENMRS_MYSQL_PORT=3306
      # Uncomment to load demo data
      - DEMO_DATA=1
      - DB_USER=root
      - DB_PASS=chahY7veeJang3Laishe
      - EXCLUDE_OPENHMIS=1
    depends_on:
      - bandahealth_bk_mysql_service
    links:
      - bandahealth_bk_mysql_service:mysql
    ports:
      - 9901:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - openmrs_bk_volume:/root/.OpenMRS
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  bandahealth_bk_mysql_service:
    container_name: bandahealth_bk_mysql
    image: mysql/mysql-server:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=chahY7veeJang3Laishe
      - MYSQL_ROOT_HOST=172.%    # Allow docker contatiners to connect to mysql
    ports:
      - 3313:3306
    healthcheck:
      test: "exit 0"
    volumes:
      - bandahealth_bk_mysql_volume:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  bandahealth_bk_mysql_volume:
  openmrs_bk_volume:
